[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install libssl-dev -y"]

[target.aarch64-unknown-linux-gnu]
image.name = "rust:latest"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-gnu"]
pre-build = ["apt-get update && apt-get install libssl-dev -y"]

[target.x86_64-unknown-linux-musl]
image.name = "alpine:latest"
image.toolchain = ["x86_64-unknown-linux-musl"]
pre-build = ["apk update && apk add openssl-dev build-base"]

[target.aarch64-unknown-linux-musl]
image.name = "alpine:latest"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl"]
pre-build = ["apk update && apk add openssl-dev build-base"]
