version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      RUST_LOG: info
      RUST_BACKTRACE: 1
      DATA_DIR: /opt/dash/data
    volumes:
      - dash-data-volume:/opt/dash/data
    networks:
      - dash
    ports:
      - 8080:8080
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dash
    volumes:
      - dash-db-volume:/var/lib/postgresql/data
    networks:
      - dash
    ports:
      - 5432:5432

volumes:
  dash-data-volume:
  dash-db-volume:

networks:
  dash:
    name: dash
    driver: bridge
